### PR TITLE
Feature/pseudonyms part 7

### PR DESCRIPTION
**Pull request by Figments**
## Description
Updates work pages with new, more compact design, and reformats them to use Pseudonyms. This is on top of various other changes, listed below.

## Changes
- Changed layout of work pages
- Added work and section editing to work and section pages
- Removed My Stuff
- Added new `tag-badge` component for more consistent, modern tag layouts
- Fixed various issues otherwise

## Areas Affected
- [x] Site Navigation
- [ ] Home
- [ ] Sign In/Out
- [ ] Registration
- [ ] Settings

.
- [x] Profile
- [x] My Stuff (main page)
- [ ] Editor
- [ ] Browse
- [ ] Work Card

.
- [x] Work Page
- [ ] Blog Page
- [ ] Collections
- [ ] Comments
- [ ] Search
- [x] Other Pages

.
- [ ] Account Authentication
- [ ] Dashboard
- [ ] Mobile

### CODE REVIEW

**Comment by Figments** [comment]
to fix in part 8: `contentId` field is missing when saving editing sections

**Comment by SigmasonicX** [comment]
Error when saving sections
```
[Nest] 37548  - 10/06/2021, 9:28:07 PM   ERROR [ExceptionsHandler] Sections validation failed: contentId: Path `contentId` is required.
ValidationError: Sections validation failed: contentId: Path `contentId` is required.
```

**Comment by SigmasonicX** [comment]
As a signed in user, I am unable to open stories published by another account.
```
ERROR Error: Uncaught (in promise): TypeError: t.content is null
fetchContent/<@http://localhost:4200/main.js:1:249491
a/</<@http://localhost:4200/main.js:1:1622618
e/s._next<@http://localhost:4200/main.js:1:1614225
```

As a signed out user, I am unable to open any stories.
```
ERROR Error: Uncaught (in promise): TypeError: this.getActive() is undefined
get currentId@http://localhost:4200/main.js:1:236244
fetchContent@http://localhost:4200/main.js:1:249325
resolve@http://localhost:4200/202.js:1:56153
```

**Review by SigmasonicX — APPROVED** [review]
Approving so fixes in part 8 can be applied

**Pull request merged**
